spring:
  datasource:
    url: jdbc:mysql://database.drivethru.top:3306/mqttold?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password: 

  # close cache
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.dashboardbackend.bean

server:
  port: 8888

pagehelper: #
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
